import { Roboto_Condensed } from "next/font/google";

const roboto = Roboto_Condensed({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
