import ThemePrivider from '@theme/themeProvider';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemePrivider>
          {children}
        </ThemePrivider>
      </body>
    </html>
  );
}
